{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.secretStore.kind }}
metadata:
  name:  {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      secretsManager:
        forceDeleteWithoutRecovery: true
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccount }}
{{- end }}
