# Helm chart values
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::215863704262:role/external-secrets-irsa
tolerations:
  - key: CriticalAddonsOnly
    operator: "Exists"
certController:
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
webhook:
  port: 9443 # To work with fargate
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
