# Helm chart values
tolerations:
  - key: CriticalAddonsOnly
    operator: "Exists"
certController:
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
webhook:
  port: 9443 # To work with fargate
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
